# Generated by Django 3.1.7 on 2021-08-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=20)),
                ('cust_email', models.EmailField(max_length=100)),
                ('cust_balance', models.IntegerField(max_length=10)),
            ],
        ),
    ]
