# Generated by Django 3.1.7 on 2021-08-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cust_balance',
            field=models.IntegerField(),
        ),
    ]
