# Generated by Django 3.1.7 on 2021-08-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_transfer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='rname',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='sname',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='acc1',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='acc2',
        ),
    ]
